#!/usr/bin/env node
// scripts/sync-config.js
// מושך את כל ההגדרות מ-CloudFormation ומעדכן קבצי config

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const STACK_NAME = process.env.STACK_NAME || 'construction-expenses-production';
const CONFIG_DIR = path.join(__dirname, '..', 'config');
const FRONTEND_PATH = path.join(__dirname, '..', 'frontend', 'index.html');

const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function getStackOutputs() {
  try {
    log('\n📡 Fetching CloudFormation outputs...', 'blue');
    
    const command = `aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query 'Stacks[0].Outputs' --output json`;
    const result = execSync(command, { encoding: 'utf8' });
    const outputs = JSON.parse(result);
    
    const config = {};
    outputs.forEach(output => {
      config[output.OutputKey] = output.OutputValue;
    });
    
    return config;
  } catch (error) {
    log('❌ Failed to fetch stack outputs', 'red');
    log('Make sure the stack is deployed and AWS CLI is configured', 'yellow');
    throw error;
  }
}

function updateEnvFile(config) {
  log('\n📝 Updating .env file...', 'blue');
  
  const envPath = path.join(__dirname, '..', '.env');
  const envContent = `# AWS Configuration - Auto-generated by sync-config.js
# Last updated: ${new Date().toISOString()}

AWS_REGION=${config.Region || 'us-east-1'}
AWS_PROFILE=default

# Cognito Configuration
COGNITO_USER_POOL_ID=${config.UserPoolId || ''}
COGNITO_CLIENT_ID=${config.UserPoolClientId || ''}
COGNITO_REGION=${config.Region || 'us-east-1'}

# API Configuration
API_ENDPOINT=${config.ApiEndpoint || ''}
API_STAGE=production

# DynamoDB Configuration
DYNAMODB_TABLE_NAME=${config.DynamoDBTableName || ''}

# Frontend Configuration
FRONTEND_S3_BUCKET=${config.FrontendBucketName || ''}
CLOUDFRONT_DISTRIBUTION_ID=${config.CloudFrontDistributionId || ''}

# Local Development
LOCAL_DEV_PORT=3000
ENABLE_DEBUG_LOGS=true

# Deployment
STACK_NAME=${STACK_NAME}
ENVIRONMENT=production
`;

  fs.writeFileSync(envPath, envContent);
  log('✅ .env file updated', 'green');
}

function updateConfigJson(config) {
  log('\n📝 Updating config/local.json...', 'blue');
  
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
  
  const configPath = path.join(CONFIG_DIR, 'local.json');
  const configData = {
    aws: {
      region: config.Region || 'us-east-1',
      profile: 'default'
    },
    cognito: {
      userPoolId: config.UserPoolId || '',
      userPoolClientId: config.UserPoolClientId || '',
      userPoolRegion: config.Region || 'us-east-1'
    },
    api: {
      endpoint: config.ApiEndpoint || '',
      stage: 'production'
    },
    dynamodb: {
      tableName: config.DynamoDBTableName || '',
      local: {
        enabled: false,
        endpoint: 'http://localhost:8000',
        tableName: 'construction-expenses-local'
      }
    },
    frontend: {
      localPort: 3000,
      s3Bucket: config.FrontendBucketName || ''
    },
    deployment: {
      stackName: STACK_NAME,
      environment: 'production'
    },
    development: {
      enableDebugLogs: true,
      mockAuth: false,
      corsOrigin: '*'
    }
  };
  
  fs.writeFileSync(configPath, JSON.stringify(configData, null, 2));
  log('✅ config/local.json updated', 'green');
}

function updateFrontendConfig(config) {
  log('\n📝 Updating frontend configuration...', 'blue');
  
  if (!fs.existsSync(FRONTEND_PATH)) {
    log('⚠️  Frontend file not found, skipping...', 'yellow');
    return;
  }
  
  let frontendContent = fs.readFileSync(FRONTEND_PATH, 'utf8');
  
  // Update AWS_CONFIG
  const configBlock = `const AWS_CONFIG = {
            region: '${config.Region || 'us-east-1'}',
            userPoolId: '${config.UserPoolId || 'YOUR_USER_POOL_ID'}',
            userPoolClientId: '${config.UserPoolClientId || 'YOUR_CLIENT_ID'}',
            apiEndpoint: '${config.ApiEndpoint || 'YOUR_API_ENDPOINT'}'
        };`;
  
  // Replace the existing config
  frontendContent = frontendContent.replace(
    /const AWS_CONFIG = \{[\s\S]*?\};/,
    configBlock
  );
  
  fs.writeFileSync(FRONTEND_PATH, frontendContent);
  log('✅ Frontend configuration updated', 'green');
}

function displayConfig(config) {
  log('\n📋 Configuration Summary:', 'blue');
  log('='.repeat(60), 'blue');
  
  const table = [
    ['API Endpoint', config.ApiEndpoint],
    ['User Pool ID', config.UserPoolId],
    ['Client ID', config.UserPoolClientId],
    ['DynamoDB Table', config.DynamoDBTableName],
    ['S3 Bucket', config.FrontendBucketName],
    ['Region', config.Region]
  ];
  
  table.forEach(([key, value]) => {
    const padding = ' '.repeat(20 - key.length);
    log(`${key}:${padding}${value}`, 'green');
  });
  
  log('='.repeat(60), 'blue');
}

async function main() {
  log('\n' + '='.repeat(60), 'blue');
  log('🔄 Configuration Sync Tool', 'blue');
  log('='.repeat(60) + '\n', 'blue');
  
  try {
    // Get stack outputs
    const config = getStackOutputs();
    
    // Update all config files
    updateEnvFile(config);
    updateConfigJson(config);
    updateFrontendConfig(config);
    
    // Display summary
    displayConfig(config);
    
    log('\n✅ All configuration files updated successfully!\n', 'green');
    log('💡 Next steps:', 'yellow');
    log('  1. Review the updated files', 'blue');
    log('  2. Test locally: npm run dev', 'blue');
    log('  3. Deploy frontend: npm run deploy:frontend\n', 'blue');
    
  } catch (error) {
    log('\n❌ Configuration sync failed!', 'red');
    console.error(error);
    process.exit(1);
  }
}

main();