AWSTemplateFormatVersion: '2010-09-09'
Description: 'Construction Expenses Tracker - Simplified AWS Infrastructure with Clerk Authentication Support'

Parameters:
  StackName:
    Type: String
    Default: 'construction-expenses-production'
    Description: 'Name of the CloudFormation stack'

  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['production', 'staging']
    Description: 'Environment name'

  # Clerk Authentication Parameters
  ClerkSecretKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: 'Clerk Secret Key for JWT verification (leave empty to disable Clerk auth)'

  ClerkPublishableKey:
    Type: String
    Default: ''
    Description: 'Clerk Publishable Key for frontend (leave empty to disable Clerk auth)'

  ClerkJWTKey:
    Type: String
    Default: ''
    NoEcho: true
    Description: 'Optional: Clerk JWT Key for specific JWT verification'

  ClerkAuthEnabled:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: 'Enable Clerk authentication (true) or use Cognito (false)'

Conditions:
  # Condition to check if Clerk authentication is enabled
  IsClerkAuthEnabled: !Equals [!Ref ClerkAuthEnabled, 'true']

Resources:
  # DynamoDB Table
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${StackName}-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: expenseId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: expenseId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${StackName}-users'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${StackName}-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30

  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt ExpensesTable.Arn
                  - !Sub '${ExpensesTable.Arn}/index/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # IAM Role for Clerk Authorizer Lambda
  ClerkAuthorizerExecutionRole:
    Type: AWS::IAM::Role
    Condition: IsClerkAuthEnabled
    Properties:
      RoleName: !Sub '${StackName}-clerk-authorizer-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # Clerk Authorizer Lambda Function
  ClerkAuthorizerFunction:
    Type: AWS::Lambda::Function
    Condition: IsClerkAuthEnabled
    Properties:
      FunctionName: !Sub '${StackName}-clerk-authorizer'
      Runtime: nodejs18.x
      Handler: clerk-authorizer.handler
      Role: !GetAtt ClerkAuthorizerExecutionRole.Arn
      Timeout: 10
      Environment:
        Variables:
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          CLERK_JWT_KEY: !Ref ClerkJWTKey
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${StackName}-api'
      Description: 'Construction Expenses Tracker API'
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Clerk JWT Authorizer for API Gateway
  ClerkJWTAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Condition: IsClerkAuthEnabled
    Properties:
      Name: !Sub '${StackName}-clerk-authorizer'
      Type: TOKEN
      AuthorizerUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ClerkAuthorizerFunction.Arn}/invocations'
      AuthorizerCredentials: !GetAtt ApiGatewayAuthorizerRole.Arn
      IdentitySource: method.request.header.Authorization
      AuthorizerResultTtlInSeconds: 300
      RestApiId: !Ref ApiGateway

  # IAM Role for API Gateway to invoke Clerk Authorizer
  ApiGatewayAuthorizerRole:
    Type: AWS::IAM::Role
    Condition: IsClerkAuthEnabled
    Properties:
      RoleName: !Sub '${StackName}-api-authorizer-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaAuthorizer
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt ClerkAuthorizerFunction.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # Lambda Permission for API Gateway to invoke Clerk Authorizer
  ClerkAuthorizerInvokePermission:
    Type: AWS::Lambda::Permission
    Condition: IsClerkAuthEnabled
    Properties:
      FunctionName: !Ref ClerkAuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/authorizers/${ClerkJWTAuthorizer}'

  # Lambda Functions with Clerk support
  GetExpensesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-get-expenses'
      Runtime: nodejs18.x
      Handler: getExpenses.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  AddExpenseFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-add-expense'
      Runtime: nodejs18.x
      Handler: addExpense.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  UpdateExpenseFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-add-expense'
      Runtime: nodejs18.x
      Handler: updateExpense.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  DeleteExpenseFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-delete-expense'
      Runtime: nodejs18.x
      Handler: deleteExpense.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  GetProjectsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-get-projects'
      Runtime: nodejs18.x
      Handler: getProjects.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  AddProjectFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-add-project'
      Runtime: nodejs18.x
      Handler: addProject.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  GetContractorsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-get-contractors'
      Runtime: nodejs18.x
      Handler: getContractors.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  AddContractorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackName}-add-contractor'
      Runtime: nodejs18.x
      Handler: addContractor.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
          CLERK_AUTH_ENABLED: !Ref ClerkAuthEnabled
          CLERK_SECRET_KEY: !Ref ClerkSecretKey
          COGNITO_AUTH_ENABLED: !If [IsClerkAuthEnabled, 'false', 'true']
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - will be replaced during deployment' })
            };
          };
      Timeout: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${StackName}-frontend-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: ConstructionExpenses

  # S3 Bucket Policy
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'

Outputs:
  ApiGatewayUrl:
    Description: 'API Gateway URL'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${StackName}-api-url'

  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref UserPool
    Export:
      Name: !Sub '${StackName}-user-pool-id'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${StackName}-user-pool-client-id'

  DynamoDBTableName:
    Description: 'DynamoDB Table Name'
    Value: !Ref ExpensesTable
    Export:
      Name: !Sub '${StackName}-table-name'

  FrontendBucketName:
    Description: 'S3 Frontend Bucket Name'
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${StackName}-frontend-bucket'

  FrontendUrl:
    Description: 'Frontend URL (S3 Website)'
    Value: !Sub 'http://${FrontendBucket}.s3-website-${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${StackName}-frontend-url'

  ClerkAuthorizerArn:
    Condition: IsClerkAuthEnabled
    Description: 'Clerk Authorizer Lambda ARN'
    Value: !GetAtt ClerkAuthorizerFunction.Arn
    Export:
      Name: !Sub '${StackName}-clerk-authorizer-arn'

  ClerkAuthorizerId:
    Condition: IsClerkAuthEnabled
    Description: 'Clerk API Gateway Authorizer ID'
    Value: !Ref ClerkJWTAuthorizer
    Export:
      Name: !Sub '${StackName}-clerk-authorizer-id'

  ClerkPublishableKey:
    Condition: IsClerkAuthEnabled
    Description: 'Clerk Publishable Key for Frontend'
    Value: !Ref ClerkPublishableKey
    Export:
      Name: !Sub '${StackName}-clerk-publishable-key'

  AuthMode:
    Description: 'Current Authentication Mode'
    Value: !If [IsClerkAuthEnabled, 'Clerk', 'Cognito']
    Export:
      Name: !Sub '${StackName}-auth-mode'
